# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vZzEMB-fmTEcmrk5Fka98KSgGnuIcfb
"""

!pip install openai

OPENAI_API = "your_openai_api_key"

import openai

# Create the OpenAI client (for v1.x)
client = openai.OpenAI(api_key=OPENAI_API)

# Your medical prompt
def get_prompt_medical():
    return (
        "You are a professional medical assistant. Analyze the following medical notes or symptoms, "
        "identify potential conditions or diagnoses, and provide clear medical insight or recommendations.\n\n"
    )

text = """
Patient reports chest tightness, shortness of breath, and elevated heart rate. Past medical history includes hypertension and mild asthma.
"""

prompt = get_prompt_medical() + text

# Send chat completion request
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

# Print response
print(response.choices[0].message.content)